export enum CmsDomainRelationType {
  RELATED = 'RELATED',
  FEATURED = 'FEATURED',
  GUIDE = 'GUIDE',
  APPLICATION = 'APPLICATION',
  REQUIREMENTS = 'REQUIREMENTS',
  ELIGIBILITY = 'ELIGIBILITY',
}
