export enum CmsDomainTargetType {
  UNIVERSITY = 'UNIVERSITY',
  ACADEMIC_PROGRAM = 'ACADEMIC_PROGRAM',
  SCHOLARSHIP = 'SCHOLARSHIP',
  MAJOR = 'MAJOR',
  INTERNATIONAL_TEST = 'INTERNATIONAL_TEST',
  COURSE = 'COURSE',
  REFERENCE_COUNTRY = 'REFERENCE_COUNTRY',
}
