export enum MajorStatus {
  IMPORTED = 'IMPORTED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  READY_TO_REVIEW = 'READY_TO_REVIEW'
}
