import {
  AcademicTaxonomyNodeType,
  AcademicTaxonomyStatus,
  AcademicStandardType,
} from './enums';

export const UNESCO_ISCED_PROVENANCE = {
  provenance: 'UNESCO_UIS_ISCED_F_2013',
  sourceVersion: '2013',
  sourceUrl: 'http://uis.unesco.org/sites/default/files/documents/isced-fields-of-education-and-training-2013-en.pdf',
};

export interface ISCEDNodeSeedInput {
  nodeType: AcademicTaxonomyNodeType;
  canonicalCode: string;
  canonicalName: string;
  description: string;
  status: AcademicTaxonomyStatus;
  standardType: AcademicStandardType;
  standardCode: string;
  localizedNames: { ar: string; en: string };
  metadata: {
    provenance: string;
    sourceVersion: string;
    sourceUrl: string;
  };
}

export const iscedFBaselineNodes: ISCEDNodeSeedInput[] = [
  // ---------------------------------------------------------------------------
  // BROAD FIELDS (2-digit, ACADEMIC_FIELD)
  // ---------------------------------------------------------------------------
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '00',
    canonicalName: 'Generic programmes and qualifications',
    description: 'ISCED Broad Field 00',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '00',
    localizedNames: { ar: 'البرامج والمؤهلات العامة', en: 'Generic programmes and qualifications' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '01',
    canonicalName: 'Education',
    description: 'ISCED Broad Field 01',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '01',
    localizedNames: { ar: 'التربية والتعليم', en: 'Education' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '02',
    canonicalName: 'Arts and humanities',
    description: 'ISCED Broad Field 02',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '02',
    localizedNames: { ar: 'الفنون والعلوم الإنسانية', en: 'Arts and humanities' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '03',
    canonicalName: 'Social sciences, journalism and information',
    description: 'ISCED Broad Field 03',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '03',
    localizedNames: { ar: 'العلوم الاجتماعية والصحافة والإعلام', en: 'Social sciences, journalism and information' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '04',
    canonicalName: 'Business, administration and law',
    description: 'ISCED Broad Field 04',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '04',
    localizedNames: { ar: 'الأعمال والإدارة والقانون', en: 'Business, administration and law' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '05',
    canonicalName: 'Natural sciences, mathematics and statistics',
    description: 'ISCED Broad Field 05',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '05',
    localizedNames: { ar: 'العلوم الطبيعية والرياضيات والإحصاء', en: 'Natural sciences, mathematics and statistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '06',
    canonicalName: 'Information and Communication Technologies (ICTs)',
    description: 'ISCED Broad Field 06',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '06',
    localizedNames: { ar: 'تكنولوجيا المعلومات والاتصالات', en: 'Information and Communication Technologies (ICTs)' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '07',
    canonicalName: 'Engineering, manufacturing and construction',
    description: 'ISCED Broad Field 07',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '07',
    localizedNames: { ar: 'الهندسة والتصنيع والبناء', en: 'Engineering, manufacturing and construction' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '08',
    canonicalName: 'Agriculture, forestry, fisheries and veterinary',
    description: 'ISCED Broad Field 08',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '08',
    localizedNames: { ar: 'الزراعة والحراجة وصيد الأسماك والبيطرة', en: 'Agriculture, forestry, fisheries and veterinary' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '09',
    canonicalName: 'Health and welfare',
    description: 'ISCED Broad Field 09',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '09',
    localizedNames: { ar: 'الصحة والرفاه', en: 'Health and welfare' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.ACADEMIC_FIELD,
    canonicalCode: '10',
    canonicalName: 'Services',
    description: 'ISCED Broad Field 10',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '10',
    localizedNames: { ar: 'الخدمات', en: 'Services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // ---------------------------------------------------------------------------
  // NARROW FIELDS (3-digit, DISCIPLINE)
  // ---------------------------------------------------------------------------
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '001',
    canonicalName: 'Basic programmes and qualifications',
    description: 'ISCED Narrow Field 001',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '001',
    localizedNames: { ar: 'البرامج والمؤهلات الأساسية', en: 'Basic programmes and qualifications' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '002',
    canonicalName: 'Literacy and numeracy',
    description: 'ISCED Narrow Field 002',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '002',
    localizedNames: { ar: 'القراءة والكتابة والحساب', en: 'Literacy and numeracy' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '003',
    canonicalName: 'Personal skills and development',
    description: 'ISCED Narrow Field 003',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '003',
    localizedNames: { ar: 'المهارات الشخصية والتطوير الذاتي', en: 'Personal skills and development' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '011',
    canonicalName: 'Education',
    description: 'ISCED Narrow Field 011',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '011',
    localizedNames: { ar: 'التربية والتعليم', en: 'Education' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '018',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving education',
    description: 'ISCED Narrow Field 018',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '018',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في التربية', en: 'Inter-disciplinary programmes and qualifications involving education' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '021',
    canonicalName: 'Arts',
    description: 'ISCED Narrow Field 021',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '021',
    localizedNames: { ar: 'الفنون', en: 'Arts' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '022',
    canonicalName: 'Humanities (except languages)',
    description: 'ISCED Narrow Field 022',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '022',
    localizedNames: { ar: 'العلوم الإنسانية (باستثناء اللغات)', en: 'Humanities (except languages)' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '023',
    canonicalName: 'Languages',
    description: 'ISCED Narrow Field 023',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '023',
    localizedNames: { ar: 'اللغات', en: 'Languages' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '028',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    description: 'ISCED Narrow Field 028',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '028',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الفنون والعلوم الإنسانية', en: 'Inter-disciplinary programmes and qualifications involving arts and humanities' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '031',
    canonicalName: 'Social and behavioural sciences',
    description: 'ISCED Narrow Field 031',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '031',
    localizedNames: { ar: 'العلوم الاجتماعية والسلوكية', en: 'Social and behavioural sciences' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '032',
    canonicalName: 'Journalism and information',
    description: 'ISCED Narrow Field 032',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '032',
    localizedNames: { ar: 'الصحافة والإعلام والمعلومات', en: 'Journalism and information' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '038',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    description: 'ISCED Narrow Field 038',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '038',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في العلوم الاجتماعية والإعلام', en: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '041',
    canonicalName: 'Business and administration',
    description: 'ISCED Narrow Field 041',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '041',
    localizedNames: { ar: 'الأعمال والإدارة', en: 'Business and administration' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '042',
    canonicalName: 'Law',
    description: 'ISCED Narrow Field 042',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '042',
    localizedNames: { ar: 'القانون', en: 'Law' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '048',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    description: 'ISCED Narrow Field 048',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '048',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الأعمال والإدارة والقانون', en: 'Inter-disciplinary programmes and qualifications involving business, administration and law' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '051',
    canonicalName: 'Biological and related sciences',
    description: 'ISCED Narrow Field 051',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '051',
    localizedNames: { ar: 'العلوم البيولوجية والعلوم ذات الصلة', en: 'Biological and related sciences' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '052',
    canonicalName: 'Environment',
    description: 'ISCED Narrow Field 052',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '052',
    localizedNames: { ar: 'البيئة', en: 'Environment' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '053',
    canonicalName: 'Physical sciences',
    description: 'ISCED Narrow Field 053',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '053',
    localizedNames: { ar: 'العلوم الفيزيائية', en: 'Physical sciences' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '054',
    canonicalName: 'Mathematics and statistics',
    description: 'ISCED Narrow Field 054',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '054',
    localizedNames: { ar: 'الرياضيات والإحصاء', en: 'Mathematics and statistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '058',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    description: 'ISCED Narrow Field 058',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '058',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في العلوم الطبيعية والرياضيات والإحصاء', en: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '061',
    canonicalName: 'Information and Communication Technologies (ICTs)',
    description: 'ISCED Narrow Field 061',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '061',
    localizedNames: { ar: 'تكنولوجيا المعلومات والاتصالات', en: 'Information and Communication Technologies (ICTs)' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '068',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving Information and Communication Technologies',
    description: 'ISCED Narrow Field 068',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '068',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في تكنولوجيا المعلومات والاتصالات', en: 'Inter-disciplinary programmes and qualifications involving Information and Communication Technologies' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '071',
    canonicalName: 'Engineering and engineering trades',
    description: 'ISCED Narrow Field 071',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '071',
    localizedNames: { ar: 'الهندسة والمهن الهندسية', en: 'Engineering and engineering trades' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '072',
    canonicalName: 'Manufacturing and processing',
    description: 'ISCED Narrow Field 072',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '072',
    localizedNames: { ar: 'التصنيع والمعالجة', en: 'Manufacturing and processing' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '073',
    canonicalName: 'Architecture and construction',
    description: 'ISCED Narrow Field 073',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '073',
    localizedNames: { ar: 'الهندسة المعمارية والبناء', en: 'Architecture and construction' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '078',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    description: 'ISCED Narrow Field 078',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '078',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الهندسة والتصنيع والبناء', en: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '081',
    canonicalName: 'Agriculture',
    description: 'ISCED Narrow Field 081',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '081',
    localizedNames: { ar: 'الزراعة', en: 'Agriculture' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '082',
    canonicalName: 'Forestry',
    description: 'ISCED Narrow Field 082',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '082',
    localizedNames: { ar: 'الحراجة والغابات', en: 'Forestry' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '083',
    canonicalName: 'Fisheries',
    description: 'ISCED Narrow Field 083',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '083',
    localizedNames: { ar: 'صيد الأسماك والثروة السمكية', en: 'Fisheries' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '084',
    canonicalName: 'Veterinary',
    description: 'ISCED Narrow Field 084',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '084',
    localizedNames: { ar: 'الطب البيطري', en: 'Veterinary' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '088',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    description: 'ISCED Narrow Field 088',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '088',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الزراعة والحراجة وصيد الأسماك والبيطرة', en: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '091',
    canonicalName: 'Health',
    description: 'ISCED Narrow Field 091',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '091',
    localizedNames: { ar: 'الصحة', en: 'Health' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '092',
    canonicalName: 'Welfare',
    description: 'ISCED Narrow Field 092',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '092',
    localizedNames: { ar: 'الرفاه الاجتماعي', en: 'Welfare' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '098',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    description: 'ISCED Narrow Field 098',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '098',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الصحة والرفاه', en: 'Inter-disciplinary programmes and qualifications involving health and welfare' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '101',
    canonicalName: 'Personal services',
    description: 'ISCED Narrow Field 101',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '101',
    localizedNames: { ar: 'الخدمات الشخصية', en: 'Personal services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '102',
    canonicalName: 'Hygiene and occupational health services',
    description: 'ISCED Narrow Field 102',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '102',
    localizedNames: { ar: 'النظافة والسلامة المهنية', en: 'Hygiene and occupational health services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '103',
    canonicalName: 'Security services',
    description: 'ISCED Narrow Field 103',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '103',
    localizedNames: { ar: 'الخدمات الأمنية', en: 'Security services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '104',
    canonicalName: 'Transport services',
    description: 'ISCED Narrow Field 104',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '104',
    localizedNames: { ar: 'خدمات النقل', en: 'Transport services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.DISCIPLINE,
    canonicalCode: '108',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving services',
    description: 'ISCED Narrow Field 108',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '108',
    localizedNames: { ar: 'البرامج والمؤهلات المتداخلة في الخدمات', en: 'Inter-disciplinary programmes and qualifications involving services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // ---------------------------------------------------------------------------
  // DETAILED FIELDS (4-digit, PROGRAM_AREA)
  // ---------------------------------------------------------------------------
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0011',
    canonicalName: 'Basic programmes and qualifications',
    description: 'ISCED Detailed Field 0011',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0011',
    localizedNames: { ar: 'البرامج والمؤهلات الأساسية', en: 'Basic programmes and qualifications' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0021',
    canonicalName: 'Literacy and numeracy',
    description: 'ISCED Detailed Field 0021',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0021',
    localizedNames: { ar: 'القراءة والكتابة والحساب', en: 'Literacy and numeracy' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0031',
    canonicalName: 'Personal skills and development',
    description: 'ISCED Detailed Field 0031',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0031',
    localizedNames: { ar: 'المهارات الشخصية والتطوير الذاتي', en: 'Personal skills and development' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 01 Education
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0111',
    canonicalName: 'Education science',
    description: 'ISCED Detailed Field 0111',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0111',
    localizedNames: { ar: 'علوم التربية', en: 'Education science' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0112',
    canonicalName: 'Training for teachers of pre-school levels',
    description: 'ISCED Detailed Field 0112',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0112',
    localizedNames: { ar: 'تدريب معلمي مرحلة ما قبل المدرسة', en: 'Training for teachers of pre-school levels' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0113',
    canonicalName: 'Teacher training without subject specialization',
    description: 'ISCED Detailed Field 0113',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0113',
    localizedNames: { ar: 'تدريب المعلمين دون تخصص في موضوع', en: 'Teacher training without subject specialization' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0114',
    canonicalName: 'Teacher training with subject specialization',
    description: 'ISCED Detailed Field 0114',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0114',
    localizedNames: { ar: 'تدريب المعلمين مع تخصص في موضوع', en: 'Teacher training with subject specialization' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0119',
    canonicalName: 'Education, not elsewhere classified',
    description: 'ISCED Detailed Field 0119',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0119',
    localizedNames: { ar: 'التربية والتعليم غير مصنفة في مكان آخر', en: 'Education, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0188',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving education',
    description: 'ISCED Detailed Field 0188',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0188',
    localizedNames: { ar: 'البرامج المتداخلة في التربية والتعليم', en: 'Inter-disciplinary programmes and qualifications involving education' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 02 Arts & Humanities
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0211',
    canonicalName: 'Audio-visual techniques and media production',
    description: 'ISCED Detailed Field 0211',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0211',
    localizedNames: { ar: 'التقنيات السمعية والبصرية وإنتاج الوسائط', en: 'Audio-visual techniques and media production' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0212',
    canonicalName: 'Fashion, interior and industrial design',
    description: 'ISCED Detailed Field 0212',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0212',
    localizedNames: { ar: 'تصميم الأزياء والتصميم الداخلي والصناعي', en: 'Fashion, interior and industrial design' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0213',
    canonicalName: 'Fine arts',
    description: 'ISCED Detailed Field 0213',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0213',
    localizedNames: { ar: 'الفنون الجميلة', en: 'Fine arts' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0214',
    canonicalName: 'Handicrafts',
    description: 'ISCED Detailed Field 0214',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0214',
    localizedNames: { ar: 'الحرف اليدوية', en: 'Handicrafts' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0215',
    canonicalName: 'Music and performing arts',
    description: 'ISCED Detailed Field 0215',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0215',
    localizedNames: { ar: 'الموسيقى والفنون الأدائية', en: 'Music and performing arts' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0219',
    canonicalName: 'Arts, not elsewhere classified',
    description: 'ISCED Detailed Field 0219',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0219',
    localizedNames: { ar: 'الفنون غير مصنفة في مكان آخر', en: 'Arts, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0221',
    canonicalName: 'Religion and theology',
    description: 'ISCED Detailed Field 0221',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0221',
    localizedNames: { ar: 'الدين واللاهوت والدراسات الإسلامية', en: 'Religion and theology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0222',
    canonicalName: 'History and archaeology',
    description: 'ISCED Detailed Field 0222',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0222',
    localizedNames: { ar: 'التاريخ والآثار', en: 'History and archaeology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0223',
    canonicalName: 'Philosophy and ethics',
    description: 'ISCED Detailed Field 0223',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0223',
    localizedNames: { ar: 'الفلسفة والأخلاقيات', en: 'Philosophy and ethics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0229',
    canonicalName: 'Humanities (except languages), not elsewhere classified',
    description: 'ISCED Detailed Field 0229',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0229',
    localizedNames: { ar: 'العلوم الإنسانية غير مصنفة في مكان آخر', en: 'Humanities (except languages), not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0231',
    canonicalName: 'Language acquisition',
    description: 'ISCED Detailed Field 0231',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0231',
    localizedNames: { ar: 'اكتساب اللغات والترجمة', en: 'Language acquisition' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0232',
    canonicalName: 'Literature and linguistics',
    description: 'ISCED Detailed Field 0232',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0232',
    localizedNames: { ar: 'الأدب واللغويات', en: 'Literature and linguistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0239',
    canonicalName: 'Languages, not elsewhere classified',
    description: 'ISCED Detailed Field 0239',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0239',
    localizedNames: { ar: 'اللغات غير مصنفة في مكان آخر', en: 'Languages, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0288',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving arts and humanities',
    description: 'ISCED Detailed Field 0288',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0288',
    localizedNames: { ar: 'البرامج المتداخلة في الفنون والعلوم الإنسانية', en: 'Inter-disciplinary programmes and qualifications involving arts and humanities' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 03 Social Sciences, Journalism and Information
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0311',
    canonicalName: 'Economics',
    description: 'ISCED Detailed Field 0311',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0311',
    localizedNames: { ar: 'علم الاقتصاد', en: 'Economics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0312',
    canonicalName: 'Political sciences and civics',
    description: 'ISCED Detailed Field 0312',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0312',
    localizedNames: { ar: 'العلوم السياسية والمواطنة', en: 'Political sciences and civics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0313',
    canonicalName: 'Psychology',
    description: 'ISCED Detailed Field 0313',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0313',
    localizedNames: { ar: 'علم النفس', en: 'Psychology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0314',
    canonicalName: 'Sociology and cultural studies',
    description: 'ISCED Detailed Field 0314',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0314',
    localizedNames: { ar: 'علم الاجتماع والدراسات الثقافية', en: 'Sociology and cultural studies' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0319',
    canonicalName: 'Social and behavioural sciences, not elsewhere classified',
    description: 'ISCED Detailed Field 0319',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0319',
    localizedNames: { ar: 'العلوم الاجتماعية والسلوكية غير مصنفة في مكان آخر', en: 'Social and behavioural sciences, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0321',
    canonicalName: 'Journalism and reporting',
    description: 'ISCED Detailed Field 0321',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0321',
    localizedNames: { ar: 'الصحافة وإعداد التقارير والإعلام', en: 'Journalism and reporting' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0322',
    canonicalName: 'Library, information and archival studies',
    description: 'ISCED Detailed Field 0322',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0322',
    localizedNames: { ar: 'المكتبات والدراسات المعلوماتية والتوثيق', en: 'Library, information and archival studies' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0329',
    canonicalName: 'Journalism and information, not elsewhere classified',
    description: 'ISCED Detailed Field 0329',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0329',
    localizedNames: { ar: 'الصحافة والمعلومات غير مصنفة في مكان آخر', en: 'Journalism and information, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0388',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information',
    description: 'ISCED Detailed Field 0388',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0388',
    localizedNames: { ar: 'البرامج المتداخلة في العلوم الاجتماعية والإعلام', en: 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 04 Business, Administration and Law
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0411',
    canonicalName: 'Accounting and taxation',
    description: 'ISCED Detailed Field 0411',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0411',
    localizedNames: { ar: 'المحاسبة والضرائب', en: 'Accounting and taxation' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0412',
    canonicalName: 'Finance, banking and insurance',
    description: 'ISCED Detailed Field 0412',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0412',
    localizedNames: { ar: 'المالية والعمليات المصرفية والتأمين', en: 'Finance, banking and insurance' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0413',
    canonicalName: 'Management and administration',
    description: 'ISCED Detailed Field 0413',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0413',
    localizedNames: { ar: 'الإدارة والأعمال', en: 'Management and administration' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0414',
    canonicalName: 'Marketing and advertising',
    description: 'ISCED Detailed Field 0414',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0414',
    localizedNames: { ar: 'التسويق والإعلان', en: 'Marketing and advertising' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0415',
    canonicalName: 'Secretarial and office work',
    description: 'ISCED Detailed Field 0415',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0415',
    localizedNames: { ar: 'السكرتارية والأعمال المكتبية', en: 'Secretarial and office work' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0416',
    canonicalName: 'Wholesale and retail sales',
    description: 'ISCED Detailed Field 0416',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0416',
    localizedNames: { ar: 'مبيعات الجملة والتجزئة', en: 'Wholesale and retail sales' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0417',
    canonicalName: 'Work skills',
    description: 'ISCED Detailed Field 0417',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0417',
    localizedNames: { ar: 'مهارات العمل', en: 'Work skills' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0419',
    canonicalName: 'Business and administration, not elsewhere classified',
    description: 'ISCED Detailed Field 0419',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0419',
    localizedNames: { ar: 'الأعمال والإدارة غير مصنفة في مكان آخر', en: 'Business and administration, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0421',
    canonicalName: 'Law',
    description: 'ISCED Detailed Field 0421',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0421',
    localizedNames: { ar: 'القانون والأنظمة', en: 'Law' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0429',
    canonicalName: 'Law, not elsewhere classified',
    description: 'ISCED Detailed Field 0429',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0429',
    localizedNames: { ar: 'القانون غير مصنف في مكان آخر', en: 'Law, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0488',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving business, administration and law',
    description: 'ISCED Detailed Field 0488',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0488',
    localizedNames: { ar: 'البرامج المتداخلة في الأعمال والقانون', en: 'Inter-disciplinary programmes and qualifications involving business, administration and law' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 05 Natural Sciences, Mathematics and Statistics
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0511',
    canonicalName: 'Biology',
    description: 'ISCED Detailed Field 0511',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0511',
    localizedNames: { ar: 'علم الأحياء', en: 'Biology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0512',
    canonicalName: 'Biochemistry',
    description: 'ISCED Detailed Field 0512',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0512',
    localizedNames: { ar: 'الكيمياء الحيوية', en: 'Biochemistry' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0519',
    canonicalName: 'Biological and related sciences, not elsewhere classified',
    description: 'ISCED Detailed Field 0519',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0519',
    localizedNames: { ar: 'العلوم البيولوجية غير مصنفة في مكان آخر', en: 'Biological and related sciences, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0521',
    canonicalName: 'Environmental sciences',
    description: 'ISCED Detailed Field 0521',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0521',
    localizedNames: { ar: 'علوم البيئة', en: 'Environmental sciences' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0522',
    canonicalName: 'Natural environments and wildlife',
    description: 'ISCED Detailed Field 0522',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0522',
    localizedNames: { ar: 'البيئات الطبيعية والحياة البرية', en: 'Natural environments and wildlife' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0529',
    canonicalName: 'Environment, not elsewhere classified',
    description: 'ISCED Detailed Field 0529',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0529',
    localizedNames: { ar: 'البيئة غير مصنفة في مكان آخر', en: 'Environment, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0531',
    canonicalName: 'Chemistry',
    description: 'ISCED Detailed Field 0531',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0531',
    localizedNames: { ar: 'الكيمياء', en: 'Chemistry' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0532',
    canonicalName: 'Earth sciences',
    description: 'ISCED Detailed Field 0532',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0532',
    localizedNames: { ar: 'علوم الأرض والجيولوجيا', en: 'Earth sciences' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0533',
    canonicalName: 'Physics',
    description: 'ISCED Detailed Field 0533',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0533',
    localizedNames: { ar: 'الفيزياء', en: 'Physics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0539',
    canonicalName: 'Physical sciences, not elsewhere classified',
    description: 'ISCED Detailed Field 0539',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0539',
    localizedNames: { ar: 'العلوم الفيزيائية غير مصنفة في مكان آخر', en: 'Physical sciences, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0541',
    canonicalName: 'Mathematics',
    description: 'ISCED Detailed Field 0541',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0541',
    localizedNames: { ar: 'الرياضيات', en: 'Mathematics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0542',
    canonicalName: 'Statistics',
    description: 'ISCED Detailed Field 0542',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0542',
    localizedNames: { ar: 'الإحصاء', en: 'Statistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0549',
    canonicalName: 'Mathematics and statistics, not elsewhere classified',
    description: 'ISCED Detailed Field 0549',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0549',
    localizedNames: { ar: 'الرياضيات والإحصاء غير مصنفة في مكان آخر', en: 'Mathematics and statistics, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0588',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics',
    description: 'ISCED Detailed Field 0588',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0588',
    localizedNames: { ar: 'البرامج المتداخلة في العلوم الطبيعية والرياضيات', en: 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 06 Information and Communication Technologies (ICTs)
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0611',
    canonicalName: 'Computer use',
    description: 'ISCED Detailed Field 0611',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0611',
    localizedNames: { ar: 'استخدام الحاسوب', en: 'Computer use' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0612',
    canonicalName: 'Database and network design and administration',
    description: 'ISCED Detailed Field 0612',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0612',
    localizedNames: { ar: 'تصميم وإدارة قواعد البيانات والشبكات', en: 'Database and network design and administration' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0613',
    canonicalName: 'Software and applications development and analysis',
    description: 'ISCED Detailed Field 0613',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0613',
    localizedNames: { ar: 'تطوير وتحليل البرمجيات والتطبيقات', en: 'Software and applications development and analysis' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0619',
    canonicalName: 'Information and Communication Technologies (ICTs), not elsewhere classified',
    description: 'ISCED Detailed Field 0619',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0619',
    localizedNames: { ar: 'تكنولوجيا المعلومات والاتصالات غير مصنفة في مكان آخر', en: 'Information and Communication Technologies (ICTs), not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0688',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving Information and Communication Technologies',
    description: 'ISCED Detailed Field 0688',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0688',
    localizedNames: { ar: 'البرامج المتداخلة في تكنولوجيا المعلومات والاتصالات', en: 'Inter-disciplinary programmes and qualifications involving Information and Communication Technologies' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 07 Engineering, Manufacturing and Construction
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0711',
    canonicalName: 'Chemical engineering and processes',
    description: 'ISCED Detailed Field 0711',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0711',
    localizedNames: { ar: 'الهندسة الكيميائية والعمليات', en: 'Chemical engineering and processes' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0712',
    canonicalName: 'Environmental protection technology',
    description: 'ISCED Detailed Field 0712',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0712',
    localizedNames: { ar: 'تقنيات حماية البيئة', en: 'Environmental protection technology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0713',
    canonicalName: 'Electricity and energy',
    description: 'ISCED Detailed Field 0713',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0713',
    localizedNames: { ar: 'الكهرباء والطاقة والهندسة الكهربائية', en: 'Electricity and energy' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0714',
    canonicalName: 'Electronics and automation',
    description: 'ISCED Detailed Field 0714',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0714',
    localizedNames: { ar: 'الإلكترونيات والأتمتة والهندسة الإلكترونية', en: 'Electronics and automation' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0715',
    canonicalName: 'Mechanics and metal trades',
    description: 'ISCED Detailed Field 0715',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0715',
    localizedNames: { ar: 'الميكانيكا والهندسة الميكانيكية', en: 'Mechanics and metal trades' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0716',
    canonicalName: 'Motor vehicles, ships and aircraft',
    description: 'ISCED Detailed Field 0716',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0716',
    localizedNames: { ar: 'المركبات ذات المحركات والسفن والطائرات', en: 'Motor vehicles, ships and aircraft' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0719',
    canonicalName: 'Engineering and engineering trades, not elsewhere classified',
    description: 'ISCED Detailed Field 0719',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0719',
    localizedNames: { ar: 'الهندسة والمهن الهندسية غير مصنفة في مكان آخر', en: 'Engineering and engineering trades, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0721',
    canonicalName: 'Food processing',
    description: 'ISCED Detailed Field 0721',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0721',
    localizedNames: { ar: 'تصنيع الأغذية', en: 'Food processing' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0722',
    canonicalName: 'Materials (glass, paper, plastic and wood)',
    description: 'ISCED Detailed Field 0722',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0722',
    localizedNames: { ar: 'المواد (الزجاج والورق والبلاستيك والخشب)', en: 'Materials (glass, paper, plastic and wood)' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0723',
    canonicalName: 'Textiles (clothes, footwear and leather)',
    description: 'ISCED Detailed Field 0723',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0723',
    localizedNames: { ar: 'المنسوجات (الملابس والأحذية والجلود)', en: 'Textiles (clothes, footwear and leather)' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0724',
    canonicalName: 'Mining and extraction',
    description: 'ISCED Detailed Field 0724',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0724',
    localizedNames: { ar: 'التعدين والاستخراج وهندسة البترول', en: 'Mining and extraction' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0729',
    canonicalName: 'Manufacturing and processing, not elsewhere classified',
    description: 'ISCED Detailed Field 0729',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0729',
    localizedNames: { ar: 'التصنيع والمعالجة غير مصنفة في مكان آخر', en: 'Manufacturing and processing, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0731',
    canonicalName: 'Architecture and town planning',
    description: 'ISCED Detailed Field 0731',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0731',
    localizedNames: { ar: 'الهندسة المعمارية والتخطيط العمراني', en: 'Architecture and town planning' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0732',
    canonicalName: 'Building and civil engineering',
    description: 'ISCED Detailed Field 0732',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0732',
    localizedNames: { ar: 'البناء والهندسة المدنية', en: 'Building and civil engineering' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0739',
    canonicalName: 'Architecture and construction, not elsewhere classified',
    description: 'ISCED Detailed Field 0739',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0739',
    localizedNames: { ar: 'الهندسة المعمارية والبناء غير مصنفة في مكان آخر', en: 'Architecture and construction, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0788',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction',
    description: 'ISCED Detailed Field 0788',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0788',
    localizedNames: { ar: 'البرامج المتداخلة في الهندسة والبناء', en: 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 08 Agriculture, Forestry, Fisheries and Veterinary
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0811',
    canonicalName: 'Crop and livestock production',
    description: 'ISCED Detailed Field 0811',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0811',
    localizedNames: { ar: 'إنتاج المحاصيل والثروة الحيوانية والعلوم الزراعية', en: 'Crop and livestock production' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0812',
    canonicalName: 'Horticulture',
    description: 'ISCED Detailed Field 0812',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0812',
    localizedNames: { ar: 'البساتين والحدائق', en: 'Horticulture' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0819',
    canonicalName: 'Agriculture, not elsewhere classified',
    description: 'ISCED Detailed Field 0819',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0819',
    localizedNames: { ar: 'الزراعة غير مصنفة في مكان آخر', en: 'Agriculture, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0821',
    canonicalName: 'Forestry',
    description: 'ISCED Detailed Field 0821',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0821',
    localizedNames: { ar: 'الحراجة والغابات', en: 'Forestry' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0831',
    canonicalName: 'Fisheries',
    description: 'ISCED Detailed Field 0831',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0831',
    localizedNames: { ar: 'صيد الأسماك والثروة السمكية', en: 'Fisheries' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0841',
    canonicalName: 'Veterinary',
    description: 'ISCED Detailed Field 0841',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0841',
    localizedNames: { ar: 'الطب البيطري', en: 'Veterinary' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0888',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary',
    description: 'ISCED Detailed Field 0888',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0888',
    localizedNames: { ar: 'البرامج المتداخلة في الزراعة والبيطرة', en: 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 09 Health and Welfare
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0911',
    canonicalName: 'Dental studies',
    description: 'ISCED Detailed Field 0911',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0911',
    localizedNames: { ar: 'طب وجراحة الأسنان', en: 'Dental studies' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0912',
    canonicalName: 'Medicine',
    description: 'ISCED Detailed Field 0912',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0912',
    localizedNames: { ar: 'الطب البشري', en: 'Medicine' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0913',
    canonicalName: 'Nursing and midwifery',
    description: 'ISCED Detailed Field 0913',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0913',
    localizedNames: { ar: 'التمريض والتوليد', en: 'Nursing and midwifery' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0914',
    canonicalName: 'Medical diagnostic and treatment technology',
    description: 'ISCED Detailed Field 0914',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0914',
    localizedNames: { ar: 'تقنيات التشخيص والعلاج الطبي', en: 'Medical diagnostic and treatment technology' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0915',
    canonicalName: 'Therapy and rehabilitation',
    description: 'ISCED Detailed Field 0915',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0915',
    localizedNames: { ar: 'العلاج الطبيعي والتأهيل', en: 'Therapy and rehabilitation' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0916',
    canonicalName: 'Pharmacy',
    description: 'ISCED Detailed Field 0916',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0916',
    localizedNames: { ar: 'الصيدلة والعلوم الصيدلية', en: 'Pharmacy' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0917',
    canonicalName: 'Traditional and complementary medicine',
    description: 'ISCED Detailed Field 0917',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0917',
    localizedNames: { ar: 'الطب التقليدي والتكميلي', en: 'Traditional and complementary medicine' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0919',
    canonicalName: 'Health, not elsewhere classified',
    description: 'ISCED Detailed Field 0919',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0919',
    localizedNames: { ar: 'الصحة غير مصنفة في مكان آخر', en: 'Health, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0921',
    canonicalName: 'Care of elderly and disabled adults',
    description: 'ISCED Detailed Field 0921',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0921',
    localizedNames: { ar: 'رعاية المسنين والمعاقين', en: 'Care of elderly and disabled adults' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0922',
    canonicalName: 'Child care and youth services',
    description: 'ISCED Detailed Field 0922',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0922',
    localizedNames: { ar: 'رعاية الأطفال وخدمات الشباب', en: 'Child care and youth services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0923',
    canonicalName: 'Social work and counselling',
    description: 'ISCED Detailed Field 0923',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0923',
    localizedNames: { ar: 'العمل الاجتماعي والإرشاد', en: 'Social work and counselling' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0929',
    canonicalName: 'Welfare, not elsewhere classified',
    description: 'ISCED Detailed Field 0929',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0929',
    localizedNames: { ar: 'الرفاه الاجتماعي غير مصنف في مكان آخر', en: 'Welfare, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '0988',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving health and welfare',
    description: 'ISCED Detailed Field 0988',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '0988',
    localizedNames: { ar: 'البرامج المتداخلة في الصحة والرفاه', en: 'Inter-disciplinary programmes and qualifications involving health and welfare' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },

  // 10 Services
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1011',
    canonicalName: 'Domestic services',
    description: 'ISCED Detailed Field 1011',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1011',
    localizedNames: { ar: 'الخدمات المنزلية', en: 'Domestic services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1012',
    canonicalName: 'Hair and beauty services',
    description: 'ISCED Detailed Field 1012',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1012',
    localizedNames: { ar: 'خدمات التجميل والعناية بالشعر', en: 'Hair and beauty services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1013',
    canonicalName: 'Hotel, restaurants and catering',
    description: 'ISCED Detailed Field 1013',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1013',
    localizedNames: { ar: 'الفندقة والمطاعم وإعداد الأطعمة', en: 'Hotel, restaurants and catering' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1014',
    canonicalName: 'Sports',
    description: 'ISCED Detailed Field 1014',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1014',
    localizedNames: { ar: 'الرياضة والتربية البدنية', en: 'Sports' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1015',
    canonicalName: 'Travel, tourism and leisure',
    description: 'ISCED Detailed Field 1015',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1015',
    localizedNames: { ar: 'السفر والسياحة والترفيه', en: 'Travel, tourism and leisure' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1019',
    canonicalName: 'Personal services, not elsewhere classified',
    description: 'ISCED Detailed Field 1019',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1019',
    localizedNames: { ar: 'الخدمات الشخصية غير مصنفة في مكان آخر', en: 'Personal services, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1021',
    canonicalName: 'Community sanitation',
    description: 'ISCED Detailed Field 1021',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1021',
    localizedNames: { ar: 'الإصحاح البيئي والمجتمعي', en: 'Community sanitation' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1022',
    canonicalName: 'Occupational health and safety',
    description: 'ISCED Detailed Field 1022',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1022',
    localizedNames: { ar: 'الصحة والسلامة المهنية', en: 'Occupational health and safety' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1029',
    canonicalName: 'Hygiene and occupational health services, not elsewhere classified',
    description: 'ISCED Detailed Field 1029',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1029',
    localizedNames: { ar: 'النظافة والسلامة المهنية غير مصنفة في مكان آخر', en: 'Hygiene and occupational health services, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1031',
    canonicalName: 'Military and defence',
    description: 'ISCED Detailed Field 1031',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1031',
    localizedNames: { ar: 'العلوم العسكرية والدفاع', en: 'Military and defence' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1032',
    canonicalName: 'Protection of persons and property',
    description: 'ISCED Detailed Field 1032',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1032',
    localizedNames: { ar: 'حماية الأشخاص والممتلكات', en: 'Protection of persons and property' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1039',
    canonicalName: 'Security services, not elsewhere classified',
    description: 'ISCED Detailed Field 1039',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1039',
    localizedNames: { ar: 'الخدمات الأمنية غير مصنفة في مكان آخر', en: 'Security services, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1041',
    canonicalName: 'Transport services',
    description: 'ISCED Detailed Field 1041',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1041',
    localizedNames: { ar: 'خدمات النقل', en: 'Transport services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1049',
    canonicalName: 'Transport services, not elsewhere classified',
    description: 'ISCED Detailed Field 1049',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1049',
    localizedNames: { ar: 'خدمات النقل غير مصنفة في مكان آخر', en: 'Transport services, not elsewhere classified' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
  {
    nodeType: AcademicTaxonomyNodeType.PROGRAM_AREA,
    canonicalCode: '1088',
    canonicalName: 'Inter-disciplinary programmes and qualifications involving services',
    description: 'ISCED Detailed Field 1088',
    status: AcademicTaxonomyStatus.ACTIVE,
    standardType: AcademicStandardType.ISCED,
    standardCode: '1088',
    localizedNames: { ar: 'البرامج المتداخلة في الخدمات', en: 'Inter-disciplinary programmes and qualifications involving services' },
    metadata: UNESCO_ISCED_PROVENANCE,
  },
];

// Build Edges automatically from Field -> Discipline -> Program Area hierarchy rules
export interface ISCEDEdgeSeedInput {
  parent: string;
  child: string;
}

export const iscedFBaselineEdges: ISCEDEdgeSeedInput[] = [
  // 00 Generic
  { parent: 'ISCED:ACADEMIC_FIELD:00', child: 'ISCED:DISCIPLINE:001' },
  { parent: 'ISCED:ACADEMIC_FIELD:00', child: 'ISCED:DISCIPLINE:002' },
  { parent: 'ISCED:ACADEMIC_FIELD:00', child: 'ISCED:DISCIPLINE:003' },
  { parent: 'ISCED:DISCIPLINE:001', child: 'ISCED:PROGRAM_AREA:0011' },
  { parent: 'ISCED:DISCIPLINE:002', child: 'ISCED:PROGRAM_AREA:0021' },
  { parent: 'ISCED:DISCIPLINE:003', child: 'ISCED:PROGRAM_AREA:0031' },

  // 01 Education
  { parent: 'ISCED:ACADEMIC_FIELD:01', child: 'ISCED:DISCIPLINE:011' },
  { parent: 'ISCED:ACADEMIC_FIELD:01', child: 'ISCED:DISCIPLINE:018' },
  { parent: 'ISCED:DISCIPLINE:011', child: 'ISCED:PROGRAM_AREA:0111' },
  { parent: 'ISCED:DISCIPLINE:011', child: 'ISCED:PROGRAM_AREA:0112' },
  { parent: 'ISCED:DISCIPLINE:011', child: 'ISCED:PROGRAM_AREA:0113' },
  { parent: 'ISCED:DISCIPLINE:011', child: 'ISCED:PROGRAM_AREA:0114' },
  { parent: 'ISCED:DISCIPLINE:011', child: 'ISCED:PROGRAM_AREA:0119' },
  { parent: 'ISCED:DISCIPLINE:018', child: 'ISCED:PROGRAM_AREA:0188' },

  // 02 Arts & Humanities
  { parent: 'ISCED:ACADEMIC_FIELD:02', child: 'ISCED:DISCIPLINE:021' },
  { parent: 'ISCED:ACADEMIC_FIELD:02', child: 'ISCED:DISCIPLINE:022' },
  { parent: 'ISCED:ACADEMIC_FIELD:02', child: 'ISCED:DISCIPLINE:023' },
  { parent: 'ISCED:ACADEMIC_FIELD:02', child: 'ISCED:DISCIPLINE:028' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0211' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0212' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0213' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0214' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0215' },
  { parent: 'ISCED:DISCIPLINE:021', child: 'ISCED:PROGRAM_AREA:0219' },
  { parent: 'ISCED:DISCIPLINE:022', child: 'ISCED:PROGRAM_AREA:0221' },
  { parent: 'ISCED:DISCIPLINE:022', child: 'ISCED:PROGRAM_AREA:0222' },
  { parent: 'ISCED:DISCIPLINE:022', child: 'ISCED:PROGRAM_AREA:0223' },
  { parent: 'ISCED:DISCIPLINE:022', child: 'ISCED:PROGRAM_AREA:0229' },
  { parent: 'ISCED:DISCIPLINE:023', child: 'ISCED:PROGRAM_AREA:0231' },
  { parent: 'ISCED:DISCIPLINE:023', child: 'ISCED:PROGRAM_AREA:0232' },
  { parent: 'ISCED:DISCIPLINE:023', child: 'ISCED:PROGRAM_AREA:0239' },
  { parent: 'ISCED:DISCIPLINE:028', child: 'ISCED:PROGRAM_AREA:0288' },

  // 03 Social Sciences, Journalism and Information
  { parent: 'ISCED:ACADEMIC_FIELD:03', child: 'ISCED:DISCIPLINE:031' },
  { parent: 'ISCED:ACADEMIC_FIELD:03', child: 'ISCED:DISCIPLINE:032' },
  { parent: 'ISCED:ACADEMIC_FIELD:03', child: 'ISCED:DISCIPLINE:038' },
  { parent: 'ISCED:DISCIPLINE:031', child: 'ISCED:PROGRAM_AREA:0311' },
  { parent: 'ISCED:DISCIPLINE:031', child: 'ISCED:PROGRAM_AREA:0312' },
  { parent: 'ISCED:DISCIPLINE:031', child: 'ISCED:PROGRAM_AREA:0313' },
  { parent: 'ISCED:DISCIPLINE:031', child: 'ISCED:PROGRAM_AREA:0314' },
  { parent: 'ISCED:DISCIPLINE:031', child: 'ISCED:PROGRAM_AREA:0319' },
  { parent: 'ISCED:DISCIPLINE:032', child: 'ISCED:PROGRAM_AREA:0321' },
  { parent: 'ISCED:DISCIPLINE:032', child: 'ISCED:PROGRAM_AREA:0322' },
  { parent: 'ISCED:DISCIPLINE:032', child: 'ISCED:PROGRAM_AREA:0329' },
  { parent: 'ISCED:DISCIPLINE:038', child: 'ISCED:PROGRAM_AREA:0388' },

  // 04 Business, Administration and Law
  { parent: 'ISCED:ACADEMIC_FIELD:04', child: 'ISCED:DISCIPLINE:041' },
  { parent: 'ISCED:ACADEMIC_FIELD:04', child: 'ISCED:DISCIPLINE:042' },
  { parent: 'ISCED:ACADEMIC_FIELD:04', child: 'ISCED:DISCIPLINE:048' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0411' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0412' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0413' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0414' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0415' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0416' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0417' },
  { parent: 'ISCED:DISCIPLINE:041', child: 'ISCED:PROGRAM_AREA:0419' },
  { parent: 'ISCED:DISCIPLINE:042', child: 'ISCED:PROGRAM_AREA:0421' },
  { parent: 'ISCED:DISCIPLINE:042', child: 'ISCED:PROGRAM_AREA:0429' },
  { parent: 'ISCED:DISCIPLINE:048', child: 'ISCED:PROGRAM_AREA:0488' },

  // 05 Natural Sciences, Mathematics and Statistics
  { parent: 'ISCED:ACADEMIC_FIELD:05', child: 'ISCED:DISCIPLINE:051' },
  { parent: 'ISCED:ACADEMIC_FIELD:05', child: 'ISCED:DISCIPLINE:052' },
  { parent: 'ISCED:ACADEMIC_FIELD:05', child: 'ISCED:DISCIPLINE:053' },
  { parent: 'ISCED:ACADEMIC_FIELD:05', child: 'ISCED:DISCIPLINE:054' },
  { parent: 'ISCED:ACADEMIC_FIELD:05', child: 'ISCED:DISCIPLINE:058' },
  { parent: 'ISCED:DISCIPLINE:051', child: 'ISCED:PROGRAM_AREA:0511' },
  { parent: 'ISCED:DISCIPLINE:051', child: 'ISCED:PROGRAM_AREA:0512' },
  { parent: 'ISCED:DISCIPLINE:051', child: 'ISCED:PROGRAM_AREA:0519' },
  { parent: 'ISCED:DISCIPLINE:052', child: 'ISCED:PROGRAM_AREA:0521' },
  { parent: 'ISCED:DISCIPLINE:052', child: 'ISCED:PROGRAM_AREA:0522' },
  { parent: 'ISCED:DISCIPLINE:052', child: 'ISCED:PROGRAM_AREA:0529' },
  { parent: 'ISCED:DISCIPLINE:053', child: 'ISCED:PROGRAM_AREA:0531' },
  { parent: 'ISCED:DISCIPLINE:053', child: 'ISCED:PROGRAM_AREA:0532' },
  { parent: 'ISCED:DISCIPLINE:053', child: 'ISCED:PROGRAM_AREA:0533' },
  { parent: 'ISCED:DISCIPLINE:053', child: 'ISCED:PROGRAM_AREA:0539' },
  { parent: 'ISCED:DISCIPLINE:054', child: 'ISCED:PROGRAM_AREA:0541' },
  { parent: 'ISCED:DISCIPLINE:054', child: 'ISCED:PROGRAM_AREA:0542' },
  { parent: 'ISCED:DISCIPLINE:054', child: 'ISCED:PROGRAM_AREA:0549' },
  { parent: 'ISCED:DISCIPLINE:058', child: 'ISCED:PROGRAM_AREA:0588' },

  // 06 Information and Communication Technologies (ICTs)
  { parent: 'ISCED:ACADEMIC_FIELD:06', child: 'ISCED:DISCIPLINE:061' },
  { parent: 'ISCED:ACADEMIC_FIELD:06', child: 'ISCED:DISCIPLINE:068' },
  { parent: 'ISCED:DISCIPLINE:061', child: 'ISCED:PROGRAM_AREA:0611' },
  { parent: 'ISCED:DISCIPLINE:061', child: 'ISCED:PROGRAM_AREA:0612' },
  { parent: 'ISCED:DISCIPLINE:061', child: 'ISCED:PROGRAM_AREA:0613' },
  { parent: 'ISCED:DISCIPLINE:061', child: 'ISCED:PROGRAM_AREA:0619' },
  { parent: 'ISCED:DISCIPLINE:068', child: 'ISCED:PROGRAM_AREA:0688' },

  // 07 Engineering, Manufacturing and Construction
  { parent: 'ISCED:ACADEMIC_FIELD:07', child: 'ISCED:DISCIPLINE:071' },
  { parent: 'ISCED:ACADEMIC_FIELD:07', child: 'ISCED:DISCIPLINE:072' },
  { parent: 'ISCED:ACADEMIC_FIELD:07', child: 'ISCED:DISCIPLINE:073' },
  { parent: 'ISCED:ACADEMIC_FIELD:07', child: 'ISCED:DISCIPLINE:078' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0711' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0712' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0713' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0714' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0715' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0716' },
  { parent: 'ISCED:DISCIPLINE:071', child: 'ISCED:PROGRAM_AREA:0719' },
  { parent: 'ISCED:DISCIPLINE:072', child: 'ISCED:PROGRAM_AREA:0721' },
  { parent: 'ISCED:DISCIPLINE:072', child: 'ISCED:PROGRAM_AREA:0722' },
  { parent: 'ISCED:DISCIPLINE:072', child: 'ISCED:PROGRAM_AREA:0723' },
  { parent: 'ISCED:DISCIPLINE:072', child: 'ISCED:PROGRAM_AREA:0724' },
  { parent: 'ISCED:DISCIPLINE:072', child: 'ISCED:PROGRAM_AREA:0729' },
  { parent: 'ISCED:DISCIPLINE:073', child: 'ISCED:PROGRAM_AREA:0731' },
  { parent: 'ISCED:DISCIPLINE:073', child: 'ISCED:PROGRAM_AREA:0732' },
  { parent: 'ISCED:DISCIPLINE:073', child: 'ISCED:PROGRAM_AREA:0739' },
  { parent: 'ISCED:DISCIPLINE:078', child: 'ISCED:PROGRAM_AREA:0788' },

  // 08 Agriculture, Forestry, Fisheries and Veterinary
  { parent: 'ISCED:ACADEMIC_FIELD:08', child: 'ISCED:DISCIPLINE:081' },
  { parent: 'ISCED:ACADEMIC_FIELD:08', child: 'ISCED:DISCIPLINE:082' },
  { parent: 'ISCED:ACADEMIC_FIELD:08', child: 'ISCED:DISCIPLINE:083' },
  { parent: 'ISCED:ACADEMIC_FIELD:08', child: 'ISCED:DISCIPLINE:084' },
  { parent: 'ISCED:ACADEMIC_FIELD:08', child: 'ISCED:DISCIPLINE:088' },
  { parent: 'ISCED:DISCIPLINE:081', child: 'ISCED:PROGRAM_AREA:0811' },
  { parent: 'ISCED:DISCIPLINE:081', child: 'ISCED:PROGRAM_AREA:0812' },
  { parent: 'ISCED:DISCIPLINE:081', child: 'ISCED:PROGRAM_AREA:0819' },
  { parent: 'ISCED:DISCIPLINE:082', child: 'ISCED:PROGRAM_AREA:0821' },
  { parent: 'ISCED:DISCIPLINE:083', child: 'ISCED:PROGRAM_AREA:0831' },
  { parent: 'ISCED:DISCIPLINE:084', child: 'ISCED:PROGRAM_AREA:0841' },
  { parent: 'ISCED:DISCIPLINE:088', child: 'ISCED:PROGRAM_AREA:0888' },

  // 09 Health and Welfare
  { parent: 'ISCED:ACADEMIC_FIELD:09', child: 'ISCED:DISCIPLINE:091' },
  { parent: 'ISCED:ACADEMIC_FIELD:09', child: 'ISCED:DISCIPLINE:092' },
  { parent: 'ISCED:ACADEMIC_FIELD:09', child: 'ISCED:DISCIPLINE:098' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0911' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0912' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0913' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0914' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0915' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0916' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0917' },
  { parent: 'ISCED:DISCIPLINE:091', child: 'ISCED:PROGRAM_AREA:0919' },
  { parent: 'ISCED:DISCIPLINE:092', child: 'ISCED:PROGRAM_AREA:0921' },
  { parent: 'ISCED:DISCIPLINE:092', child: 'ISCED:PROGRAM_AREA:0922' },
  { parent: 'ISCED:DISCIPLINE:092', child: 'ISCED:PROGRAM_AREA:0923' },
  { parent: 'ISCED:DISCIPLINE:092', child: 'ISCED:PROGRAM_AREA:0929' },
  { parent: 'ISCED:DISCIPLINE:098', child: 'ISCED:PROGRAM_AREA:0988' },

  // 10 Services
  { parent: 'ISCED:ACADEMIC_FIELD:10', child: 'ISCED:DISCIPLINE:101' },
  { parent: 'ISCED:ACADEMIC_FIELD:10', child: 'ISCED:DISCIPLINE:102' },
  { parent: 'ISCED:ACADEMIC_FIELD:10', child: 'ISCED:DISCIPLINE:103' },
  { parent: 'ISCED:ACADEMIC_FIELD:10', child: 'ISCED:DISCIPLINE:104' },
  { parent: 'ISCED:ACADEMIC_FIELD:10', child: 'ISCED:DISCIPLINE:108' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1011' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1012' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1013' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1014' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1015' },
  { parent: 'ISCED:DISCIPLINE:101', child: 'ISCED:PROGRAM_AREA:1019' },
  { parent: 'ISCED:DISCIPLINE:102', child: 'ISCED:PROGRAM_AREA:1021' },
  { parent: 'ISCED:DISCIPLINE:102', child: 'ISCED:PROGRAM_AREA:1022' },
  { parent: 'ISCED:DISCIPLINE:102', child: 'ISCED:PROGRAM_AREA:1029' },
  { parent: 'ISCED:DISCIPLINE:103', child: 'ISCED:PROGRAM_AREA:1031' },
  { parent: 'ISCED:DISCIPLINE:103', child: 'ISCED:PROGRAM_AREA:1032' },
  { parent: 'ISCED:DISCIPLINE:103', child: 'ISCED:PROGRAM_AREA:1039' },
  { parent: 'ISCED:DISCIPLINE:104', child: 'ISCED:PROGRAM_AREA:1041' },
  { parent: 'ISCED:DISCIPLINE:104', child: 'ISCED:PROGRAM_AREA:1049' },
  { parent: 'ISCED:DISCIPLINE:108', child: 'ISCED:PROGRAM_AREA:1088' },
];

export interface ISCEDAliasSeedInput {
  nodeKey: string;
  locale: string;
  alias: string;
}

export const iscedFBaselineAliases: ISCEDAliasSeedInput[] = [
  // 06 ICT
  { nodeKey: 'ISCED:ACADEMIC_FIELD:06', locale: 'en', alias: 'ICT' },
  { nodeKey: 'ISCED:ACADEMIC_FIELD:06', locale: 'ar', alias: 'تكنولوجيا المعلومات والاتصالات' },
  { nodeKey: 'ISCED:DISCIPLINE:061', locale: 'en', alias: 'Computer Science' },
  { nodeKey: 'ISCED:DISCIPLINE:061', locale: 'ar', alias: 'علوم الحاسب' },
  { nodeKey: 'ISCED:DISCIPLINE:061', locale: 'ar', alias: 'علوم الحاسوب' },
  { nodeKey: 'ISCED:DISCIPLINE:061', locale: 'en', alias: 'Information Technology' },
  { nodeKey: 'ISCED:DISCIPLINE:061', locale: 'ar', alias: 'تقنية المعلومات' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0613', locale: 'en', alias: 'Software Engineering' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0613', locale: 'ar', alias: 'هندسة البرمجيات' },

  // 09 Health
  { nodeKey: 'ISCED:PROGRAM_AREA:0912', locale: 'en', alias: 'General Medicine' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0912', locale: 'ar', alias: 'الطب والجراحة' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0911', locale: 'en', alias: 'Dentistry' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0911', locale: 'ar', alias: 'طب الأسنان' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0916', locale: 'en', alias: 'Pharmacy' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0916', locale: 'ar', alias: 'الصيدلة' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0913', locale: 'en', alias: 'Nursing' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0913', locale: 'ar', alias: 'التمريض' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0915', locale: 'en', alias: 'Physical Therapy' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0915', locale: 'ar', alias: 'العلاج الطبيعي' },

  // 07 Engineering
  { nodeKey: 'ISCED:PROGRAM_AREA:0731', locale: 'en', alias: 'Architecture' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0731', locale: 'ar', alias: 'الهندسة المعمارية' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0732', locale: 'en', alias: 'Civil Engineering' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0732', locale: 'ar', alias: 'الهندسة المدنية' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0715', locale: 'en', alias: 'Mechanical Engineering' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0715', locale: 'ar', alias: 'الهندسة الميكانيكية' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0713', locale: 'en', alias: 'Electrical Engineering' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0713', locale: 'ar', alias: 'الهندسة الكهربائية' },

  // 04 Business & Law
  { nodeKey: 'ISCED:PROGRAM_AREA:0411', locale: 'en', alias: 'Accounting' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0411', locale: 'ar', alias: 'المحاسبة' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0412', locale: 'en', alias: 'Finance' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0412', locale: 'ar', alias: 'المالية والتمويل' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0413', locale: 'en', alias: 'Business Administration' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0413', locale: 'ar', alias: 'إدارة الأعمال' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0421', locale: 'en', alias: 'Law' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0421', locale: 'ar', alias: 'القانون والأنظمة' },

  // 02 Humanities
  { nodeKey: 'ISCED:PROGRAM_AREA:0221', locale: 'ar', alias: 'الدراسات الإسلامية' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0221', locale: 'ar', alias: 'الشريعة' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0232', locale: 'ar', alias: 'اللغة العربية وآدابها' },
  { nodeKey: 'ISCED:PROGRAM_AREA:0231', locale: 'ar', alias: 'اللغة الإنجليزية والترجمة' },
];

export interface ISCEDMappingSeedInput {
  sourceKey: string;
  targetStandard: string;
  targetCode: string;
  strength: string;
}

export const iscedFBaselineMappings: ISCEDMappingSeedInput[] = [
  { sourceKey: 'ISCED:PROGRAM_AREA:0613', targetStandard: 'CIP', targetCode: '11.0201', strength: 'EXACT' },
];
