import { afterEach, describe, expect, it } from 'vitest';
import { promises as fs } from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { InMemoryImportRawSnapshotStore } from '../../src/import-foundation/InMemoryImportRawSnapshotStore'; import { LocalImportRawSnapshotStore } from '../../src/import-foundation/LocalImportRawSnapshotStore';
const roots: string[] = []; const acquisition = { sourceId: 'source-1', connectorId: 'official-api', connectorVersion: '2.0.0', requestedUrl: 'https://example.com/start', finalUrl: 'https://example.com/final', statusCode: 200, contentType: 'application/json', contentLength: 3, rawBytes: new Uint8Array([1,2,3]), fetchedAt: new Date('2026-08-23T00:00:00Z'), etag: 'etag-1', lastModified: 'Sat, 23 Aug 2026 00:00:00 GMT' };
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))); });
describe('raw snapshot stores', () => {
  it('retains equivalent truthful provenance in memory', async () => { const store = new InMemoryImportRawSnapshotStore(); const saved = await store.store(acquisition); expect(await store.get(saved.artifactId)).toEqual(saved); expect(saved).not.toHaveProperty('statusCode', undefined); });
  it('writes exact idempotent bytes and atomic hash-named metadata locally', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'manaratak-raw-')); roots.push(root); const store = new LocalImportRawSnapshotStore(root); const first = await store.store(acquisition); const second = await store.store(acquisition); expect(second.artifactId).toBe(first.artifactId); expect(Buffer.from(await fs.readFile(first.rawArtifactReference))).toEqual(Buffer.from(acquisition.rawBytes)); const loaded = await store.get(first.artifactId); expect(loaded).toMatchObject({ sourceId: 'source-1', connectorId: 'official-api', requestedUrl: acquisition.requestedUrl, finalUrl: acquisition.finalUrl, statusCode: 200, contentType: 'application/json', etag: 'etag-1' }); expect((await fs.readdir(root)).sort()).toEqual([`${first.artifactId}.bin`, `${first.artifactId}.json`]); });
  it('rejects caller-controlled retrieval paths', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'manaratak-raw-')); roots.push(root); expect(await new LocalImportRawSnapshotStore(root).get('../secret')).toBeNull(); });
});
